-- MySQL Script generated by MySQL Workbench
-- qui 12 dez 2019 01:04:39 -02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema busclick
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema busclick
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `busclick` DEFAULT CHARACTER SET utf8 ;
USE `busclick` ;

-- -----------------------------------------------------
-- Table `busclick`.`Tb_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `busclick`.`Tb_cliente` (
  `Id_Cliente` DECIMAL(10,0) NOT NULL,
  `Nome_Cliente` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Telefone` DECIMAL(10,0) NULL,
  `Endereco` VARCHAR(45) NULL,
  `UF` VARCHAR(2) NULL,
  `Estado` VARCHAR(45) NULL,
  `CEP` DECIMAL(10,0) NULL,
  PRIMARY KEY (`Id_Cliente`, `Email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `busclick`.`tb_UraTelefonica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `busclick`.`tb_UraTelefonica` (
  `id_UraTelefonica` DECIMAL(10,0) NULL,
  `Data` DATE NULL,
  `Time` TIME NULL,
  `fila_descricao` VARCHAR(45) NULL,
  `Agente` VARCHAR(45) NULL,
  `Status` VARCHAR(45) NULL,
  `Telefone` DECIMAL(10,0) NULL,
  `Estado` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `fila_de_atendimento` VARCHAR(45) NULL,
  `duracao_espera_fila` TIME NULL,
  `duracao_atendimento` TIME NULL,
  `duracao_total_da_chamada` TIME NULL,
  `Classificacao` VARCHAR(45) NULL,
  `Sub_classificacao` VARCHAR(45) NULL,
  PRIMARY KEY (`id_UraTelefonica`),
  INDEX `fk_tb_UraTelefonica_1_idx` (`email` ASC),
  CONSTRAINT `fk_tb_UraTelefonica_1`
    FOREIGN KEY (`email`)
    REFERENCES `busclick`.`Tb_cliente` (`Email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `busclick`.`tb_chatonline`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `busclick`.`tb_chatonline` (
  `id_chatonline` INT NULL,
  `dt_data_inicio` DATETIME NULL,
  `dt_data_fim` DATETIME NULL,
  `Semana` DECIMAL(10,0) NULL,
  `Agente` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `feedback_response_additional` VARCHAR(45) NULL,
  `feedback_average` DECIMAL(10,0) NULL,
  `Atendido` VARCHAR(45) NULL,
  PRIMARY KEY (`id_chatonline`),
  INDEX `fk_tb_chatonline_1_idx` (`email` ASC),
  CONSTRAINT `fk_tb_chatonline_1`
    FOREIGN KEY (`email`)
    REFERENCES `busclick`.`Tb_cliente` (`Email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `busclick`.`tb_whatsapp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `busclick`.`tb_whatsapp` (
  `id_whatsapp` DECIMAL(10,0) NULL,
  `Inicio_conversa` DATETIME NULL,
  `fim_conversa` DATETIME NULL,
  `fim_conversa_final` DATETIME NULL,
  `duracao_atendimento` TIME NULL,
  `Finalizado` TINYINT(1) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id_whatsapp`),
  INDEX `fk_tb_whatsapp_1_idx` (`email` ASC),
  CONSTRAINT `fk_tb_whatsapp_1`
    FOREIGN KEY (`email`)
    REFERENCES `busclick`.`Tb_cliente` (`Email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `busclick`.`tb_email`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `busclick`.`tb_email` (
  `idtb_email` DECIMAL(10,0) NULL,
  `site` VARCHAR(45) NULL,
  `loja` VARCHAR(45) NULL,
  `semana` DECIMAL(10,0) NULL,
  `dt_abertuta` DATETIME NULL,
  `dt_fechamento` DATETIME NULL,
  `Sub_classificacao` VARCHAR(45) NULL,
  `Classificacao` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`idtb_email`),
  INDEX `fk_tb_email_1_idx` (`email` ASC),
  CONSTRAINT `fk_tb_email_1`
    FOREIGN KEY (`email`)
    REFERENCES `busclick`.`Tb_cliente` (`Email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
